/**
 * @file    errmsg.h
 * @brief   Error messages for the AMPL-2023 compiler.
 * @author  W.H.K. Bester (whkbester@cs.sun.ac.za)
 * @date    2023-07-03
 */

#ifndef ERRMSG_H
#define ERRMSG_H

typedef enum
{
	ERR_EXPECT,
	ERR_EXPECTED_EXPRESSION_OR_ARRAY_ALLOCATION,
	ERR_EXPECTED_EXPRESSION_OR_STRING,
	ERR_EXPECTED_FACTOR,
	ERR_EXPECTED_SCALAR,
	ERR_EXPECTED_STATEMENT,
	ERR_EXPECTED_TYPE_SPECIFIER,
	ERR_ILLEGAL_ARRAY_OPERATION,
	ERR_MISSING_RETURN_EXPRESSION,
	ERR_MULTIPLE_DEFINITION,
	ERR_NOT_AN_ARRAY,
	ERR_NOT_A_FUNCTION,
	ERR_NOT_A_PROCEDURE,
	ERR_NOT_A_VARIABLE,
	ERR_RETURN_EXPRESSION_NOT_ALLOWED,
	ERR_TOO_FEW_ARGUMENTS,
	ERR_TOO_MANY_ARGUMENTS,
	ERR_UNKNOWN_IDENTIFIER,
	ERR_UNREACHABLE
} Error;

#endif /* ERRMSG_H */
